name: Build and Deploy Telegram Bot

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Clone telegram-ext repository
        run: git clone https://github.com/python-telegram-bot/python-telegram-bot.git

      - name: Install telegram-ext
        run: |
          cd python-telegram-bot
          pip install -e .

      - name: Build bot
        run: python bot.py

      - name: Deploy bot
        uses: actions/upload-artifact@v3
        with:
          name: telegram-bot
          path: bot.py

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: telegram-bot
          path: bot.py

      - name: Run bot
        run: python bot.py
